[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "alternative-thumbnails copy-video-url custom-player-overlay-opacity disable-shorts-on-startup disable-auto-captions disable-player-popup-panels disable-zoom-haptics external-downloads hdr-auto-brightness hide-shorts-components hide-ads hide-breaking-news-shelf hide-player-buttons hide-watermark minimized-playback navigation-buttons old-video-quality-menu open-links-externally playback-speed remember-video-quality return-youtube-dislike seekbar-tapping sponsorblock swipe-controls vanced-microg-support video-ads"
exclusive-patches = true

