[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'Bypass URL redirects' 'Open links externally' 'Disable zoom haptics' 'Spoof device dimensions' 'Minimized playback' 'Vanced MicroG support' 'Remember video quality' 'Old video quality menu' 'HDR auto brightness' 'Playback speed' 'Video ads' 'Hide ads' 'Copy video url' 'Swipe controls' 'Seekbar tapping' 'External downloads' 'Hide breaking news shelf' 'Hide Shorts components' 'Hide layout components' 'Alternative thumbnails' 'Disable auto captions' 'Disable Shorts on startup' 'SponsorBlock' 'Custom player overlay opacity' 'Navigation buttons' 'Hide player buttons' 'Disable player popup panels' 'Return YouTube Dislike'"
exclusive-patches = true

