logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "copy-video-url disable-player-popup-panels disable-shorts-on-startup downloads hdr-auto-brightness hide-ads hide-breaking-news-shelf hide-get-premium hide-player-overlay	hide-watermark minimized-playback old-quality-layout remember-video-quality remove-player-button-background	return-youtube-dislike seekbar-tapping sponsorblock swipe-controls video-ads video-speed"                                                 # space-seperated patches to include (non-excluded patches are included by default)
exclusive-patches = true
version = "auto"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
exclusive-patches = false                                             # excludes all patches by default and only applies included-patches
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
