logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
excluded-patches = "'Theme' 'Tablet mini player' 'Hide autoplay button' 'Hide captions button' 'Hide video action buttons' 'Hide cast button' 'Spoof app version' 'Premium heading' 'Enable tablet layout' 'Comments' 'Hide info cards' 'Hide floating microphone button' 'Hide album cards' 'Hide crowdfunding box' 'Hide email address' 'Player flyout menu' 'Hide endscreen cards' 'Hide filter bar' 'Hide 'Load more' button' 'Disable rolling number animations' 'Hide seekbar' 'Hide timestamp' 'Disable suggested video end screen' 'Wide searchbar' 'Disable precise seeking gesture' 'Enable debugging' 'Always autorepeat' 'Client spoof' 'Announcements'"
