[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
included-patches = "'External downloads' 'Copy video url' 'Seekbar tapping' 'Swipe controls' 'Hide ads' 'Video ads' 'Old video quality menu' 'Playback speed' 'HDR auto brightness' 'Remember video quality' 'Vanced MicroG support' 'Minimized playback' 'Disable zoom haptics' 'Bypass URL redirects' 'Open links externally' 'Hide breaking news shelf' 'Hide watermark' 'Hide Shorts components' 'Navigation buttons' 'Hide player buttons' 'Disable auto captions' 'Disable Shorts on startup' 'Disable player popup panels' 'SponsorBlock' 'Return YouTube Dislike' 'Alternative thumbnails' 'Custom player overlay opacity'"
exclusive-patches = true

